In [2]:
# NumPy
# By convention, the numPy module imported under the alias np.
import numpy as np

In [ ]:
# NumPy arrays are homogeneous, all elements have the same data type

In [10]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
data[0]

array([1, 2])

In [5]:
data[0][0]

1

In [6]:
data.shape # a tuple that contains the number of elements

(3, 2)

In [7]:
data.size # the total number elements in the array

6

In [8]:
data.ndim # number of dimensions (axes)

2

In [9]:
data.dtype # the data type of the elements in the array.

dtype('int32')

In [12]:
array = np.array([1, 2, 3], dtype=np.int)
array

array([1, 2, 3])

In [13]:
array = np.array([1, 2, 3], dtype=np.float)
array

array([1., 2., 3.])

In [14]:
array = np.array([1, 2, 3], dtype=np.complex)
array

array([1.+0.j, 2.+0.j, 3.+0.j])

In [15]:
# create a new copy with type-casted array values
array = np.array(array, dtype=np.int)
array

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: ComplexWarning: Casting complex values to real discards the imaginary part
  


array([1, 2, 3])

In [17]:
array = array.astype(np.float)
array

array([1., 2., 3.])

In [18]:
np.sqrt(np.array([-1, 0, 1]))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([nan,  0.,  1.])

In [19]:
#square root of each element in an array (j=sqrt(-1))
np.sqrt(np.array([-1, 0, 1],dtype=np.complex))

array([0.+1.j, 0.+0.j, 1.+0.j])

In [23]:
# real part of the complex numbers in a vector
np.array([1j, 0, 1]).real

array([0., 0., 1.])

In [22]:
# real part of the complex numbers in a vector
np.real([1j, 0, 1])

array([0., 0., 1.])

In [24]:
# imaginary part of the complex numbers in a vector
np.array([1j, 0, 1]).imag

array([1., 0., 0.])

In [25]:
# imaginary part of the complex numbers in a vector
np.imag([1j, 0, 1])

array([1., 0., 0.])

In [ ]:
# row-major format: store the rows of the array after each other
order= 'C'

In [ ]:
# column-major format
order = 'F'

In [ ]:
# default format is row-major

In [ ]:
# NumPy array attribute ndarray.strides defines exactly how this mapping is done

In [27]:
# help(np)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [28]:
# create an array with the specified dimensions and data type that is filled with zeros.
np.zeros([2,3], dtype=np.int)

array([[0, 0, 0],
       [0, 0, 0]])

In [29]:
# create an array with the specified dimensions and data type that is filled with ones.
np.ones([2,3], dtype=np.int)

array([[1, 1, 1],
       [1, 1, 1]])

In [32]:
# creates a diagonal array with specified values along the diagonal and zeros elsewhere.
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [33]:
np.array(range(0,10,2))

array([0, 2, 4, 6, 8])

In [74]:
# creates an array with evenly spaced values between the specified start, end, and increment values.
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [77]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [82]:
# creates an array with evenly spaced values between specified start and end values, using a specified number of elements.
# endpoint is included by default (endpoint=True)
np.linspace(0,8,5, dtype=np.int)

array([0, 2, 4, 6, 8])

In [81]:
np.linspace(0,10,5, dtype=np.int, endpoint=False)

array([0, 2, 4, 6, 8])

In [41]:
np.linspace(0,10,11, dtype=np.int)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
# creates an array with values that are logarithmically spaced between the given start and end values.
# first two arguments, for the start and end values, are the powers of the optional base keyword argument 
# (which defaults to 10)
# generate logarithmically distributed numbers between e^0=1 and e^1=e
np.logspace(0,1,10, base=np.exp(1), dtype=np.float)

array([1.        , 1.11751907, 1.24884887, 1.39561243, 1.5596235 ,
       1.742909  , 1.94773404, 2.17662993, 2.43242545, 2.71828183])

In [ ]:
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])
X, Y = np.meshgrid(x, y)
Z = (X + Y) ** 2

In [ ]:
# Alternatively, the functions np.mgrid and np.ogrid can also be used to generate coordinate arrays, 
# using a slightly different syntax based on indexing and slice objects.

In [ ]:
# np.fromfunction

In [ ]:
# np.fromfile

In [ ]:
# np.genfromtxt

In [44]:
# np.loadtxt

In [45]:
# uniform: U(0,1)
np.random.rand(10)

array([0.8622844 , 0.90196056, 0.39017011, 0.24404175, 0.95093867,
       0.98241909, 0.43823164, 0.74741812, 0.58557671, 0.49719057])

In [53]:
# standard normal: N(0,1)
np.random.randn(10)

array([-1.14627909,  1.81402413, -0.35546622, -0.2338537 , -0.30876076,
       -0.26490098, -1.54812302, -0.13868312,  1.84340124,  1.80579202])

In [49]:
# discrete uniform: U(0,10)
np.random.randint(10)

4

In [50]:
np.random.random_integers(0,5,10)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 5 + 1) instead
  """Entry point for launching an IPython kernel.


array([1, 4, 5, 4, 4, 2, 4, 0, 4, 3])

In [51]:
np.random.randint(5, size=10)

array([0, 4, 1, 4, 4, 2, 1, 2, 1, 2])

In [54]:
# create a two-dimensional array by using nested lists
np.array([[1,2],[2,3],[3,4]])

array([[1, 2],
       [2, 3],
       [3, 4]])

In [55]:
np.matrix([[1,2],[2,3],[3,4]])

matrix([[1, 2],
        [2, 3],
        [3, 4]])

In [56]:
M = np.matrix([[1,2],[2,3]])
M

matrix([[1, 2],
        [2, 3]])

In [58]:
N = np.matrix([[0,1],[1,0]])
N

matrix([[0, 1],
        [1, 0]])

In [59]:
M*N

matrix([[2, 1],
        [3, 2]])

In [60]:
M**2

matrix([[ 5,  8],
        [ 8, 13]])

In [61]:
np.exp(M)

matrix([[ 2.71828183,  7.3890561 ],
        [ 7.3890561 , 20.08553692]])

In [62]:
I = np.ones([2,2], dtype=np.int)

In [63]:
5 * I

array([[5, 5],
       [5, 5]])

In [64]:
# np.full is slightly more efficient since it avoids the multiplication
np.full([2,2], 5)

array([[5, 5],
       [5, 5]])

In [70]:
# generate an array with uninitialized values, of the given size
X = np.empty(5, dtype=np.int)

In [71]:
X.fill(2)
X

array([2, 2, 2, 2, 2])

In [73]:
Y = np.full(5, 2)
Y

array([2, 2, 2, 2, 2])

In [ ]:
# Creating arrays with properties of other arrays