In [1]:
import pandas as pd
import numpy as np

In [2]:
# Series: constitutes the data structure designed to accommodate a sequence of one-dimensional data

In [3]:
s = pd.Series([12,-4,7,9])
s

0    12
1    -4
2     7
3     9
dtype: int64

In [4]:
s[0]

12

In [5]:
s[-1]

KeyError: -1

In [6]:
s.index[0]

0

In [7]:
s[s.index[0]]

12

In [8]:
s[s.index[-1]]

9

In [9]:
s = pd.Series([12,-4,7,9], index=['a','b','c','d'])
s

a    12
b    -4
c     7
d     9
dtype: int64

In [11]:
s = pd.Series([12,-4,7,9], index=['a','b','c','d'], dtype=np.float)
s

a    12.0
b    -4.0
c     7.0
d     9.0
dtype: float64

In [12]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [13]:
s.values

array([12., -4.,  7.,  9.])

In [14]:
s[2]

7.0

In [15]:
s['c']

7.0

In [16]:
s[0:2]

a    12.0
b    -4.0
dtype: float64

In [17]:
s[['b','c']]

b   -4.0
c    7.0
dtype: float64

In [18]:
# assign new values to elements

In [1]:
# dataframes
# A DataFrame represents a rectangular table of data and contains an ordered collection of columns, 
# each of which can be a different value type (numeric, string, boolean, etc.). 

#The DataFrame has both a row and column index; it can be thought of as a dict of Series all sharing the same index.

In [4]:
df = pd.DataFrame([[1,2],[3,4],[5,6]])
df

0  1
0  1  2
1  3  4
2  5  6

In [5]:
df = pd.DataFrame([[1,2], [3,4], [5,6]], columns=['A', 'B'])
df

A  B
0  1  2
1  3  4
2  5  6

In [17]:
df = pd.DataFrame([[1,2], [3,4], [5,6]], columns=['A', 'B'], index=['row_' + str(i) for i in range(3)])
df

A  B
row_0  1  2
row_1  3  4
row_2  5  6

In [18]:
df.index

Index(['row_0', 'row_1', 'row_2'], dtype='object')

In [19]:
df.columns

Index(['A', 'B'], dtype='object')

In [20]:
df.reset_index()

index  A  B
0  row_0  1  2
1  row_1  3  4
2  row_2  5  6

In [21]:
df.reset_index(drop=False)

index  A  B
0  row_0  1  2
1  row_1  3  4
2  row_2  5  6

In [22]:
df

A  B
row_0  1  2
row_1  3  4
row_2  5  6

In [23]:
df.reset_index(drop=True)

A  B
0  1  2
1  3  4
2  5  6

In [24]:
df

A  B
row_0  1  2
row_1  3  4
row_2  5  6

In [27]:
df = df.reset_index(drop=True)
df

A  B
0  1  2
1  3  4
2  5  6

In [28]:
df['A']

0    1
1    3
2    5
Name: A, dtype: int64

In [29]:
df['A']>=3

0    False
1     True
2     True
Name: A, dtype: bool

In [30]:
df[df['A']>=3]

A  B
1  3  4
2  5  6

In [31]:
df

A  B
0  1  2
1  3  4
2  5  6

In [33]:
df['C']=df['B']+1
df

A  B  C
0  1  2  3
1  3  4  5
2  5  6  7

In [34]:
df['D']=df['B']+df['C']
df

True

In [ ]:
2 in df['B']

In [35]:
# set name of df’s index attribute
df.index.name = 'rows'
df

A  B  C
rows         
0     1  2  3
1     3  4  5
2     5  6  7

In [36]:
# set name of df’s columns attribute
df.columns.name = 'columns'
df

columns  A  B  C
rows            
0        1  2  3
1        3  4  5
2        5  6  7

In [37]:
df.columns= ['X','Y','Z']
df

X  Y  Z
rows         
0     1  2  3
1     3  4  5
2     5  6  7

In [42]:
d = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 
     'year': [2000, 2001, 2002, 2001, 2002, 2003], 
     'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [43]:
df = pd.DataFrame(d)
df

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [40]:
df.head() #shows the first five rows by detault

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [41]:
df.head(3)

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7
2  Ohio  2002  3.6

In [45]:
df2 = pd.DataFrame(d, columns=['year', 'state', 'pop', 'debt'], 
                   index=['one', 'two', 'three', 'four', 'five', 'six'])
df2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [46]:
df2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [47]:
df2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [48]:
df2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [51]:
df2['debt'] = np.arange(6)
df2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [52]:
debt = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

df2['debt']=debt

In [54]:
df2['debt']=debt
df2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [56]:
pd.isnull(df2['debt'])

one       True
two      False
three     True
four     False
five     False
six       True
Name: debt, dtype: bool

In [62]:
df2['debt'].isnull()

one       True
two      False
three     True
four     False
five     False
six       True
Name: debt, dtype: bool

In [63]:
df2[df2['debt'].isnull()]

year   state  pop  debt
one    2000    Ohio  1.5   NaN
three  2002    Ohio  3.6   NaN
six    2003  Nevada  3.2   NaN

In [64]:
df2[~df2['debt'].isnull()]

year   state  pop  debt
two   2001    Ohio  1.7  -1.2
four  2001  Nevada  2.4  -1.5
five  2002  Nevada  2.9  -1.7

In [59]:
pd.notnull(df2['debt'])

one      False
two       True
three    False
four      True
five      True
six      False
Name: debt, dtype: bool

In [60]:
df2['debt'].notnull()

one      False
two       True
three    False
four      True
five      True
six      False
Name: debt, dtype: bool

In [67]:
df2[~df2['debt'].isnull()]

year   state  pop  debt
two   2001    Ohio  1.7  -1.2
four  2001  Nevada  2.4  -1.5
five  2002  Nevada  2.9  -1.7

In [68]:
df2[df2['debt'].notnull()]

year   state  pop  debt
two   2001    Ohio  1.7  -1.2
four  2001  Nevada  2.4  -1.5
five  2002  Nevada  2.9  -1.7

In [73]:
df2['eastern'] = df2.state == 'Ohio'
df2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [74]:
del df2['eastern']

In [75]:
d = {'Nevada': {2001: 2.4, 2002: 2.9},
     'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [76]:
df3 = pd.DataFrame(d)
df3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [77]:
df3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [78]:
d = {'Ohio': df3['Ohio'][:-1], 
     'Nevada': df3['Nevada'][:2]}

In [79]:
df4 = pd.DataFrame(d)
df4

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [80]:
df = pd.Series(range(3), index=['a', 'b', 'c'])

In [81]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [82]:
labels = pd.Index(np.arange(3))

In [83]:
df = pd.Series([1.5, -2.5, 0], index=labels)
df

0    1.5
1   -2.5
2    0.0
dtype: float64

In [84]:
df.index is labels

True

In [86]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [87]:
df.reindex(['a', 'b', 'c', 'd', 'e'])

a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
dtype: float64

In [88]:
df

0    1.5
1   -2.5
2    0.0
dtype: float64

In [90]:
df = pd.DataFrame(np.arange(9).reshape((3, 3)),
                  index=['a', 'c', 'd'],
                  columns=['Ohio', 'Texas', 'California'])
df

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [92]:
df = df.reindex(['a', 'b', 'c', 'd'])
df

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [93]:
states = ['Texas', 'Utah', 'California']

In [94]:
df.reindex(columns=states)
df

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [96]:
df.loc[['a', 'b', 'c', 'd']]

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [97]:
df.loc['a', 'Ohio']

0.0

In [98]:
df.loc[['a', 'b'], 'Ohio']

a    0.0
b    NaN
Name: Ohio, dtype: float64

In [99]:
df.loc[['a', 'b'], ['Ohio','Texas']]

Ohio  Texas
a   0.0    1.0
b   NaN    NaN

In [101]:
df.drop('Ohio',axis=1)

Texas  California
a    1.0         2.0
b    NaN         NaN
c    4.0         5.0
d    7.0         8.0

In [102]:
df

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [103]:
# Many functions, like drop, which modify the size or shape of a Series or DataFrame,
# can manipulate an object in-place without returning a new object:
df.drop('Ohio',axis=1, inplace=True)

In [104]:
df

Texas  California
a    1.0         2.0
b    NaN         NaN
c    4.0         5.0
d    7.0         8.0

In [105]:
df = pd.DataFrame(np.arange(16).reshape((4, 4)),
                  index=['Ohio', 'Colorado', 'Utah', 'New York'],
                  columns=['one', 'two', 'three', 'four'])

In [106]:
df.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [107]:
df.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [109]:
df

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [110]:
df=df.T

In [111]:
df

Ohio  Colorado  Utah  New York
one       0         4     8        12
two       1         5     9        13
three     2         6    10        14
four      3         7    11        15

In [112]:
df['Colorado']

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int32

In [114]:
df['Colorado']['one']

4

In [115]:
df['Colorado'][0]

4

In [116]:
df['Colorado'][2:4]

three    6
four     7
Name: Colorado, dtype: int32

In [117]:
df['Colorado'][['three','four','one']]

three    6
four     7
one      4
Name: Colorado, dtype: int32

In [118]:
df[df['Colorado']>=5]

Ohio  Colorado  Utah  New York
two       1         5     9        13
three     2         6    10        14
four      3         7    11        15

In [119]:
# Slicing with labels behaves differently than normal Python slicing in that the endpoint is inclusive:
df['two','five']

KeyError: ('two', 'five')

In [120]:
s = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
s

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [121]:
s['b':'c']

b    1.0
c    2.0
dtype: float64

In [122]:
# Setting using these methods modifies the corresponding section of the Series:
s['b':'c'] = 5

In [123]:
s

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [133]:
df = pd.DataFrame(np.arange(16).reshape((4, 4)),
                  index=['Ohio', 'Colorado', 'Utah', 'New York'],
                  columns=['one', 'two', 'three', 'four'])

In [125]:
df

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [127]:
# Passing a single element to select a column.
df['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [128]:
# Passing a list to select columns based on the list.
df[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [130]:
# The row selection syntax df[:2] is provided as a convenience.
df[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [131]:
# Another use case is in indexing with a boolean DataFrame, such as one produced by a scalar comparison:
df < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [134]:
df[df < 5]

one  two  three  four
Ohio      0.0  1.0    2.0   3.0
Colorado  4.0  NaN    NaN   NaN
Utah      NaN  NaN    NaN   NaN
New York  NaN  NaN    NaN   NaN

In [135]:
df[df < 5] = 0

In [136]:
df

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [137]:
df.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [138]:
df.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [139]:
df.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [140]:
df.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [141]:
df.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [142]:
df.iloc[:, :3][df.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [ ]:
# Selects single column or subset of columns by integer position
df.iloc[:, where]
# Select both rows and columns by integer position
df.iloc[where_i, where_j] 
# Select a single scalar value by row and column label
df.at[label_i, label_j] 
# Select a single scalar value by row and column position (integers)
df.iat[i, j] 
# Select either rows or columns by labels
reindex method 
# Select single value by row and column label
get_value, set_value methods 

In [143]:
s = pd.Series(np.arange(3))
s

0    0
1    1
2    2
dtype: int32

In [144]:
# avoid this!!!
s[-1]

KeyError: -1

In [147]:
s[s.index[-1]]

2

In [148]:
# On the other hand, with a non-integer index, there is no potential for ambiguity:
s = pd.Series(np.arange(3), index=['a', 'b', 'c'])

In [149]:
s[-1]

2

In [150]:
# To keep things consistent, if you have an axis index containing integers, 
# data selection will always be label-oriented. For more precise handling, use loc (for labels) or iloc (for integers)
s[:1]

a    0
dtype: int32

In [151]:
s.loc[:1]

TypeError: cannot do slice indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [1] of <class 'int'>

In [152]:
s.iloc[:1]

a    0
dtype: int32

In [159]:
df1 = pd.DataFrame(np.arange(9).reshape((3, 3)), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [160]:
df2 = pd.DataFrame(np.arange(12).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df2

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [161]:
# Since the 'c' and 'e' columns are not found in both DataFrame objects, they appear as all missing in the result.
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [162]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})
df1 + df2

A   B
0 NaN NaN
1 NaN NaN

In [163]:
df1 = pd.DataFrame(np.arange(12).reshape((3, 4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20).reshape((4, 5)), columns=list('abcde'))
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [164]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [165]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [166]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [167]:
df1.reindex(columns=df2.columns, fill_value=0)

a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

In [169]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [170]:
arr[0]

array([0, 1, 2, 3])

In [171]:
arr - arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [ ]:
# Operations between a DataFrame and a Series are similar:

In [174]:
df = pd.DataFrame(np.arange(12).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [175]:
df - df.iloc[0]

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [176]:
# If an index value is not found in either the DataFrame’s columns or the Series’s index,
# the objects will be reindexed to form the union:
s = pd.Series(range(3), index=['b', 'e', 'f'])

In [177]:
df + s

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [179]:
# If you want to instead broadcast over the columns, matching on the rows, you have to use one of the arithmetic methods.
df.sub(df['d'], axis='index')

b  d  e
Utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1

In [ ]:
# NumPy ufuncs (element-wise array methods) also work with pandas objects:

In [181]:
df = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df

b         d         e
Utah    0.877566  1.305726 -0.068685
Ohio    0.075493  0.263309  0.297432
Texas   1.562652 -0.233054 -1.971653
Oregon -2.250788 -0.625226  0.533285

In [182]:
f = lambda x: x.max() - x.min()

In [183]:
df.apply(f)

b    3.813440
d    1.930951
e    2.504938
dtype: float64

In [184]:
df.apply(f, axis='columns')

Utah      1.374411
Ohio      0.221939
Texas     3.534305
Oregon    2.784073
dtype: float64

In [185]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [186]:
df.apply(f)

b         d         e
min -2.250788 -0.625226 -1.971653
max  1.562652  1.305726  0.533285

In [187]:
format = lambda x: '%.2f' % x

In [188]:
df.applymap(format)

b      d      e
Utah     0.88   1.31  -0.07
Ohio     0.08   0.26   0.30
Texas    1.56  -0.23  -1.97
Oregon  -2.25  -0.63   0.53

In [189]:
# The reason for the name applymap is that Series has a map method for applying an element-wise function:
df['e'].map(format)

Utah      -0.07
Ohio       0.30
Texas     -1.97
Oregon     0.53
Name: e, dtype: object

In [191]:
# Sorting and Ranking
s = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
s

d    0
a    1
b    2
c    3
dtype: int64

In [192]:
s.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [194]:
s.sort_index(ascending=False)

d    0
c    3
b    2
a    1
dtype: int64

In [195]:
df = pd.DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'], columns=['d', 'a', 'b', 'c'])
df

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [196]:
df.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [197]:
df.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [ ]:
s = pd.Series([4, 7, -3, 2])

In [198]:
df = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
df

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [199]:
df.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [200]:
df.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [201]:
df = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1], 'c': [-2, 5, 8, -2.5]})
df

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [202]:
df.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [203]:
df.rank(axis='index')

b    a    c
0  3.0  1.5  2.0
1  4.0  3.5  3.0
2  1.0  1.5  4.0
3  2.0  3.5  1.0

In [204]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [210]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], 
                  index=['a', 'b', 'c', 'd'], columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [211]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [212]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [213]:
# NA values are excluded unless the entire slice (row or column in this case) is NA.
# This can be disabled with the skipna option:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [214]:
df.idxmax()

one    b
two    d
dtype: object

In [215]:
# methods are accumulations:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [216]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [ ]:
'''
Number of non-NA values
count 
Compute set of summary statistics for Series or each DataFrame column
describe
Compute minimum and maximum values
min, max
Compute index locations (integers) at which minimum or maximum value obtained, respectively
argmin, argmax
Compute index labels at which minimum or maximum value obtained, respectively
idxmin, idxmax
Compute sample quantile ranging from 0 to 1
quantile
Sum of values
sum 
Mean of values
mean
Arithmetic median (50% quantile) of values
median
Mean absolute deviation from mean value
mad
Product of all values
prod
Sample variance of values
var
Sample standard deviation of values
std
Sample skewness (third moment) of values
skew
Sample kurtosis (fourth moment) of values
kurt
Cumulative sum of values
cumsum
Cumulative minimum or maximum of values, respectively
cummin, cummax
Cumulative product of values
cumprod
Compute first arithmetic difference (useful for time series)
diff
Compute percent changes
pct_change 

'''

In [ ]:
# Correlation and Covariance

In [2]:
# conda update -n base -c defaults conda
# conda install -c anaconda pandas-datareader
import pandas_datareader.data as web

In [3]:
all_data = {ticker: web.get_data_yahoo(ticker) for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [4]:
price = pd.DataFrame({ticker: data['Adj Close'] for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume'] for ticker, data in all_data.items()})

In [5]:
returns = price.pct_change()

In [ ]:
# The corr method of Series computes the correlation of the overlapping, non-NA, 
# aligned-by-index values in two Series. Relatedly, cov computes the covariance:

In [6]:
returns['MSFT'].corr(returns['IBM'])

0.4779337539035761

In [7]:
returns['MSFT'].cov(returns['IBM'])

9.302586989659925e-05

In [8]:
# DataFrame’s corr and cov methods, on the other hand, return a full correlation or 
# covariance matrix as a DataFrame, respectively:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.395252  0.575074  0.521372
IBM   0.395252  1.000000  0.477934  0.402806
MSFT  0.575074  0.477934  1.000000  0.651418
GOOG  0.521372  0.402806  0.651418  1.000000

In [9]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000248  0.000082  0.000134  0.000125
IBM   0.000082  0.000172  0.000093  0.000080
MSFT  0.000134  0.000093  0.000220  0.000147
GOOG  0.000125  0.000080  0.000147  0.000232

In [10]:
# compute pairwise correlations between a DataFrame’s columns or rows with another Series or DataFrame.
returns.corrwith(returns.IBM)

AAPL    0.395252
IBM     1.000000
MSFT    0.477934
GOOG    0.402806
dtype: float64

In [11]:
returns.corrwith(volume)

AAPL   -0.109227
IBM    -0.157430
MSFT   -0.082989
GOOG   -0.013763
dtype: float64

In [12]:
x = [1, 5, 25, 125, 625]

In [17]:
df = pd.DataFrame(np.random.choice(x, (5,6), p=[0.4, 0.1, 0.1, 0.3, 0.1]))
df

0    1    2    3    4    5
0  625    5  125   25  625   25
1    5  625  125  125  625   25
2    1  125  125    5   25  125
3  125    1  125    1    1    1
4    5    1    1    1  625  125

In [19]:
df[0].unique()

array([625,   5,   1, 125], dtype=int64)

In [21]:
df[0].value_counts()

5      2
125    1
1      1
625    1
Name: 0, dtype: int64

In [23]:
pd.value_counts(df[0].values, sort=False)

625    1
1      1
125    1
5      2
dtype: int64

In [26]:
mask = df.isin([1, 5])
mask

0      1      2      3      4      5
0  False   True  False  False  False  False
1   True  False  False  False  False  False
2   True  False  False   True  False  False
3  False   True  False   True   True   True
4   True   True   True   True  False  False

In [27]:
df[mask]

0    1    2    3    4    5
0  NaN  5.0  NaN  NaN  NaN  NaN
1  5.0  NaN  NaN  NaN  NaN  NaN
2  1.0  NaN  NaN  5.0  NaN  NaN
3  NaN  1.0  NaN  1.0  1.0  1.0
4  5.0  1.0  1.0  1.0  NaN  NaN

In [ ]:
# Related to isin is the Index.get_indexer method, which gives you an index array
# from an array of possibly non-distinct values into another array of distinct values:

In [28]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [29]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [30]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [ ]:
# Compute boolean array indicating whether each Series value is contained in the passed sequence of
isin
# Compute integer indices for each value in an array into another array of distinct values; 
# helpful for data values alignment and join-type operations
match 
# Compute array of unique values in a Series, returned in the order observed
unique
# Return a Series containing unique values as its index and frequencies as its values, ordered count in descending order
value_counts 

In [32]:
# compute a histogram on multiple related columns in a DataFrame.
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [35]:
result = data.apply(pd.value_counts).fillna(0)
result
# The row labels in the result are the distinct values occurring in all of the columns.
# The values are the respective counts of these values in each column.

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [ ]:
df = pd.read_csv('examples/ex1.csv')
pd.read_table('examples/ex1.csv', sep=',')
pd.read_csv('examples/ex2.csv', header=None)

In [36]:
!cat examples/ex4.csv
# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

'cat' is not recognized as an internal or external command,
operable program or batch file.


NameError: name 'a' is not defined