In [2]:
import numpy as np

In [181]:
class TowerOfHanoi:
    # default constructor 
    def __init__(self, N=3): 
        self.disk = np.ones(N, dtype=np.int)
        self.size = len(self.disk)
        self.peg = tuple(np.arange(1, 4))
        
    def states(self):
        print(self.disk)
        print(self.peg)
        
    def print_peg(self, p):
        print([i for i in range(len(self.disk)) if self.disk[i] ==p])
    
    def move(self, d, p):
        if self.is_valid_move(d, p):
            self.disk[d] = p
            if self.is_winner():
                print("Congratulations! You win!")
        else:
            print("Invalid move")
    
    def is_winner(self):
        winner_flag=False
        for p in self.peg[1:]:
            if np.all(self.disk == p * np.ones(self.size, dtype=np.int)):
                return True
        return False
        
    def is_valid_move(self, d, p):
        if p in self.peg:
            disks_on_p = [i for i in range(len(self.disk)) if self.disk[i] == p]
            if len(disks_on_p) > 0:
                if np.max(disks_on_p) < d:
                    return False
                else:
                    return True
            else:
                return True
        else:
            return False

In [182]:
Game = TowerOfHanoi(2)
Game.states()

[1 1]
(1, 2, 3)


In [183]:
Game.move(0,2)
Game.states()

[2 1]
(1, 2, 3)


In [185]:
Game.move(1,3)
Game.states()


[2 3]
(1, 2, 3)


In [186]:
Game.move(0,3)
Game.states()

Congratulations! You win!
[3 3]
(1, 2, 3)


In [80]:
Game.disk

array([2, 1, 1, 1])

In [82]:
np.all(Game.disk == np.array([2,1,1,1]))

True

[1 1 1 1]
(1, 2, 3)


In [189]:
np.prod(range(1,5))

24

In [191]:
'24'.isnumeric()

True

In [194]:
n='24'
n.isnumeric()

True

In [195]:
n=input("Gimme yo numberrrro: ")

Gimme yo numberrrro: 100


In [196]:
n.isnumeric()

True

In [197]:
if n.isnumeric():
    n=int(n)
else:
    print("Heeey! Ain't a number brooo")
        

In [198]:
type(n)

int

In [203]:
t=complex(1+1j)
t.isnumeric()

AttributeError: 'complex' object has no attribute 'isnumeric'

In [204]:
100.is_integer()

SyntaxError: invalid syntax (<ipython-input-204-0506eb3cf28b>, line 1)

1


[3 1 1 1]
(1, 2, 3)


In [19]:
t=tuple(np.arange(1, 4))
t

(1, 2, 3)

In [22]:
5 in t

False

In [65]:
d=np.ones(4, dtype=np.int)
d

array([1, 1, 1, 1])

In [76]:
np.all(d == np.ones(4, dtype=np.int))

True

In [68]:
np.logical_and(d)

ValueError: invalid number of arguments

In [69]:
np.all(d)

True

In [74]:
g = np.array([False, False])

In [75]:
np.all(g)

False

In [27]:
d[0]=2
d

array([2, 1, 1, 1])

In [38]:
# disks on peg1 ??
Game.disk

array([4, 1, 1, 1])

In [40]:
[i for i in range(len(Game.disk)) if Game.disk[i] in [1]]

[1, 2, 3]

In [35]:
L=[1,4,6,4,5,7,3,4]
L

[1, 4, 6, 4, 5, 7, 3, 4]

In [36]:
[i for i in range(len(L)) if L[i] in [4, 5]]

[1, 3, 4, 7]

In [34]:
x =L[L == 10]
x

1